// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using appspbox.context;

namespace appspbox.Migrations
{
    [DbContext(typeof(productDbContext))]
    [Migration("20210405014700_Context PostDbContext")]
    partial class ContextPostDbContext
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.4");

            modelBuilder.Entity("appspbox.Models.Orders", b =>
                {
                    b.Property<int>("orderrId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("description")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("identity")
                        .HasColumnType("int");

                    b.Property<string>("name")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("orderrId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("appspbox.Models.Product", b =>
                {
                    b.Property<int>("productId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("description")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("name")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("orderrId")
                        .HasColumnType("int");

                    b.Property<int>("price")
                        .HasColumnType("int");

                    b.Property<int>("quantity")
                        .HasColumnType("int");

                    b.HasKey("productId");

                    b.HasIndex("orderrId");

                    b.ToTable("Product");
                });

            modelBuilder.Entity("appspbox.Models.Provider", b =>
                {
                    b.Property<int>("providerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("description")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("direction")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("name")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("phone")
                        .HasColumnType("int");

                    b.HasKey("providerId");

                    b.ToTable("Provider");
                });

            modelBuilder.Entity("appspbox.Models.Product", b =>
                {
                    b.HasOne("appspbox.Models.Orders", "GetOrders")
                        .WithMany("GetProducts")
                        .HasForeignKey("orderrId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GetOrders");
                });

            modelBuilder.Entity("appspbox.Models.Orders", b =>
                {
                    b.Navigation("GetProducts");
                });
#pragma warning restore 612, 618
        }
    }
}
